# Generated by Django 5.2.6 on 2025-10-05 16:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['blog', 'ip_address'], name='blog_app_vi_blog_id_6f430f_idx'),
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['viewed_at'], name='blog_app_vi_viewed__5b8a23_idx'),
        ),
    ]
